# Generated by Django 4.1.1 on 2022-09-07 15:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hr_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate_Full_Name', models.CharField(max_length=500)),
                ('Date_of_Birth', models.DateField()),
                ('Years_of_Experience', models.IntegerField(max_length=2)),
                ('Department_ID', models.CharField(choices=[('IT', 'January'), ('HR', 'February'), ('Finance', 'March')], default='IT', max_length=9)),
                ('Resume', models.FileField(upload_to='documents/%Y/%m/%d', validators=[main.models.validate_file_extension])),
            ],
        ),
    ]
