# Generated by Django 4.1.1 on 2022-09-08 06:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_hr_db_resume_alter_hr_db_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr_db',
            name='Resume',
            field=models.FileField(default='exit', upload_to='documents/%Y/%m/%d', validators=[main.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
