# Generated by Django 4.1.1 on 2022-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hr_db_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr_db',
            name='Years_of_Experience',
            field=models.IntegerField(),
        ),
    ]
